### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samhh** [liamg/traitor#14]
Hi there :slightly_smiling_face: 

I'm packaging this for the [AUR](https://aur.archlinux.org) and can't find a license. On what terms is this software made available?

Cheers!

**Comment by liamg** [comment]
Awesome, it's under MIT, I've added the license now :+1:

**Comment by samhh** [comment]
Appreciated! You can find the AUR package [here](https://aur.archlinux.org/packages/traitor-bin/).

On an unrelated note, is it intentional that 0.0.2 on the releases page doesn't currently have any prebuilt binaries?

**Comment by liamg** [comment]
Thanks! That's fixed now, teething problems with GH actions 😄
