### ISSUE TITLE
Run the program without checking exp

### ISSUE THREAD

**Issue by xiaoheiwo** [liamg/traitor#42]
![image](https://user-images.githubusercontent.com/37685546/122542398-371b3d00-d05d-11eb-8c51-b0e5001618ea.png)
I run the program on several different computers, but there is no test vulnerability information, as shown in the figure. Is it because I don't have an exp。
Or because the server does not have vulnerabilities

**Comment by liamg** [comment]
Hey @xiaoheiwo, this is because traitor hasn’t found any vulnerabilities, the machines are likely patched against the polkit cve and have no permissive sudo rules etc.
