### ISSUE TITLE
how do you run this script?

### ISSUE THREAD

**Issue by philmacrack** [liamg/traitor#55]
i dont know how you run or install this as there is no clear documentation, all help is greatly appreciated

**Comment by prologic** [comment]
> i dont know how you run or install this as there is no clear documentation, all help is greatly appreciated

First of all.

- This is not a "script".

`trator` is a computer program written in Go that compiles to native machine go.

Second; Did you even bother to read the [Getting Traitor](https://github.com/liamg/traitor#getting-traitor) guide at all that's clearly marked on the README?! 🤦‍♂️ I can understand if you missed it, but it's _right_ there.

**Comment by prologic** [comment]
@liamg if you add me as a Collaborator to your project, I can help manage some of these silly issues 😅 -- This one for example can be closed as a case of "PEBKAC" 😅

**Comment by liamg** [comment]
@prologic Thanks, I’ve spread myself a bit thin lately 😅. I’ll add you now 👍

**Comment by prologic** [comment]
No worries I hear ya 😆
